<script setup lang='ts'>
import { onMounted, ref } from 'vue'
import { NButton, NDivider, NInput, NQrCode, NSpin, NStep, NSteps } from 'naive-ui'
import type { MFAConfig } from '@/components/admin/model'
import { fetchDisableUserMFA, fetchGetUserMFA, fetchVerifyUserMFA } from '@/api'

const loading = ref(false)
const saving = ref(false)
const config = ref<MFAConfig>()

async function fetchConfig() {
  try {
    loading.value = true
    const { data } = await fetchGetUserMFA<MFAConfig>()
    config.value = data
  }
  finally {
    loading.value = false
  }
}

async function updateMFAInfo() {
  saving.value = true
  try {
    if (!config.value)
      throw new Error('Invalid')
    const result = await fetchVerifyUserMFA(config.value.secretKey, config.value.testCode)
    await fetchConfig()
    window.$message?.success(result.message as string)
  }
  catch (error: any) {
    window.$message?.error(error.message)
  }
  saving.value = false
}

async function disableMFA() {
  saving.value = true
  try {
    if (!config.value)
      throw new Error('Invalid')
    const result = await fetchDisableUserMFA(config.value.testCode)
    await fetchConfig()
    window.$message?.success(result.message as string)
  }
  catch (error: any) {
    window.$message?.error(error.message)
  }
  saving.value = false
}

onMounted(() => {
  fetchConfig()
})
</script>

<template>
  <NSpin :show="loading">
    <div class="p-4 space-y-5 min-h-[200px]">
      <div class="flex-1 items-center space-y-1">
        <p>
          Multi-factor authentication
          <a class="mx-1.5 rounded px-1 py-0.5 text-xs font-semibold" :class="config && config.enabled ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'">{{ config && config.enabled ? 'Enabled' : 'Disabled' }}</a>
        </p>
        <p>An additional security layer that enhances the security of your login experience.</p>
      </div>
      <div v-if="config && config.enabled" class="flex flex-col space-y-2">
        <div>
          <p class="text-xs text-black/60 dark:text-white/50 text-left">
            Enter the 6-digit dynamic verification code to disable the Multi-factor authentication.<br>
            Note: If you have lost your phone or cannot use one-time code, please contact at <a href="mailto:support@axiomaibd.com" class="text-[var(--primary-color)]">support@axiomaibd.com</a>
          </p>
        </div>
        <div class="w-[200px]">
          <NInput
            :value="config && config.testCode"
            placeholder="Enter 6-digit code"
            @input="(val) => { if (config) config.testCode = val }"
          />
        </div>
      </div>
      <div v-if="config && config.enabled" class="flex items-center space-x-4">
        <div class="flex flex-wrap items-center gap-4">
          <NButton :loading="saving" type="error" :disabled="!config || !config.testCode || config.testCode.length !== 6" @click="disableMFA()">
            {{ $t('setting.disableMFA') }}
          </NButton>
        </div>
      </div>
      <NDivider v-if="!config || !config.enabled" />
      <div v-if="!config || !config.enabled" class="flex items-center space-x-4">
        <div class="flex-1">
          <NSteps vertical>
            <NStep title="Installation of the Authenticator App" description="Install an authenticator app: Google Authenticator, Microsoft Authenticator, Authy, etc." />
            <NStep title="Configure to generate one-time code">
              <p class="mb-2">
                Scan the QR Code below using your preferred authenticator app and then enter the provided one-time code below.
              </p>
              <div class="bg-white px-2 inline-block">
                <NQrCode :value="config?.otpauthUrl" :size="150" error-correction-level="H" type="svg" :padding="0" class="mt-2 mb-2" />
              </div>
              <p class="mt-2">
                Note: Authenticator can't scan the verification code? Manually add the following account information:
              </p>Account: <a class="font-bold">{{ config?.userName }}</a><br> Key: <a class="font-bold">{{ config?.secretKey }}</a>
            </NStep>
            <NStep title="Verify and enable">
              <p class="mb-2">
                Please enter the 6-digit one-time code generated by the authenticator app to enable the Multi-factor authentication.
              </p>
              <div class="flex items-center space-x-4">
                <div class="w-[200px]">
                  <NInput
                    :value="config && config.testCode"
                    placeholder="Enter 6-digit code"
                    @input="(val) => { if (config) config.testCode = val }"
                  /><br><br>
                  <NButton :loading="saving" type="primary" :disabled="!config || !config.testCode || config.testCode.length !== 6" @click="updateMFAInfo()">
                    {{ $t('setting.enableMFA') }}
                  </NButton>
                </div>
              </div>
              <br>FAQ: How do I turn off Multi-factor authentication?<br>1. After logging in, go to settings > Security and enter the 6-digit verification code.<br>2. Contact us at <a href="mailto:support@axiomaibd.com" class="text-[var(--primary-color)]">support@axiomaibd.com</a> to disable Multi-factor authentication.
            </NStep>
          </NSteps>
        </div>
      </div>
      <div v-if="!config || !config.enabled" class="flex items-center space-x-4">
        <div class="flex flex-wrap items-center gap-4" />
      </div>
    </div>
  </NSpin>
</template>
