<script setup lang='ts'>
import { onMounted, ref } from 'vue'
import { NButton, NDivider, NInput, NSpin, NStep, NSteps, useMessage } from 'naive-ui'
import QrcodeVue from 'qrcode.vue'
import type { TwoFAConfig } from '@/components/admin/model'
import { fetchDisableUser2FA, fetchGetUser2FA, fetchVerifyUser2FA } from '@/api'

const ms = useMessage()
const loading = ref(false)
const saving = ref(false)
const config = ref<TwoFAConfig>()
async function fetchConfig() {
  try {
    loading.value = true
    const { data } = await fetchGetUser2FA<TwoFAConfig>()
    config.value = data
  }
  finally {
    loading.value = false
  }
}
async function update2FAInfo() {
  saving.value = true
  try {
    if (!config.value)
      throw new Error('Invalid')
    const result = await fetchVerifyUser2FA(config.value.secretKey, config.value.testCode)
    await fetchConfig()
    ms.success(result.message as string)
  }
  catch (error: any) {
    ms.error(error.message)
  }
  saving.value = false
}
async function disable2FA() {
  saving.value = true
  try {
    if (!config.value)
      throw new Error('Invalid')
    const result = await fetchDisableUser2FA(config.value.testCode)
    await fetchConfig()
    ms.success(result.message as string)
  }
  catch (error: any) {
    ms.error(error.message)
  }
  saving.value = false
}
onMounted(() => {
  fetchConfig()
})
</script>

<template>
  <NSpin :show="loading">
    <div class="p-4 space-y-5 min-h-[200px]">
      <div class="space-y-6">
        <div class="flex items-center space-x-4">
          <div class="flex-1">
            Two-step verification is an additional verification step that makes your login experience more secure. With two-step verification turned on, you will be prompted to enter a dynamic verification code each time you want to log in to your account.
            <br> Current Status:
            <span v-if="!config || !config.enabled" style="color: red;">Disabled</span>
            <span v-if="config && config.enabled" style="color: rgb(22, 183, 65);">Enabled</span>
          </div>
        </div>
        <div v-if="config && config.enabled" class="flex items-center space-x-4">
          <div class="w-[200px]">
            <NInput
              :value="config && config.testCode"
              placeholder="6-digit dynamic code"
              @input="(val) => { if (config) config.testCode = val }"
            />
          </div>
        </div>
        <div v-if="config && config.enabled" class="flex items-center space-x-4">
          <div class="flex flex-wrap items-center gap-4">
            <NButton
              :loading="saving" type="warning" @click="disable2FA()"
            >
              {{ $t('setting.disable2FA') }}
            </NButton>
          </div>
        </div>
        <NDivider v-if="!config || !config.enabled" />
        <div v-if="!config || !config.enabled" class="flex items-center space-x-4">
          <div class="flex-1">
            <NSteps vertical>
              <NStep
                title="Installation of the Authenticator App"
                description="Install an authenticator app, such as Google Authenticator, Microsoft Authenticator, Authy, etc."
              />
              <NStep
                title="Configure to generate verification code"
              >
                Open the Authenticator App and click "Scan QR Code" to scan the QR code.
                <br><br>
                <QrcodeVue :value="config?.otpauthUrl" :size="150" level="H" />
                <br>Note: Authenticator can't scan the verification code? Manually add the following account:<br> Account: {{ config?.userName }}<br> Key: {{ config?.secretKey }}
              </NStep>
              <NStep
                title="Verify and enable"
              >
                Please enter the 6-digit dynamic verification code generated by the Authenticator App to enable two-step verification.
                <br>
                <div class="flex items-center space-x-4">
                  <div class="w-[200px]">
                    <NInput
                      :value="config && config.testCode"
                      placeholder=""
                      @input="(val) => { if (config) config.testCode = val }"
                    /><br><br>
                    <NButton
                      :loading="saving" type="primary" :disabled="!config || !config.testCode || config.testCode.length !== 6"
                      @click="update2FAInfo()"
                    >
                      {{ $t('setting.enable2FA') }}
                    </NButton>
                  </div>
                </div>
                <br>Note: How do I turn off two-step verification?<br>1. After logging in, use the two-step verification code on the Two-Step Verification page to close it.<br>2. Contact at support@axiomaibd.com to reset your password to disable two-step verification.
              </NStep>
            </NSteps>
          </div>
        </div>
        <div v-if="!config || !config.enabled" class="flex items-center space-x-4">
          <div class="flex flex-wrap items-center gap-4" />
        </div>
      </div>
    </div>
  </NSpin>
</template>
