<script setup lang='ts'>
import { onMounted, ref } from 'vue'
import { NButton, NDivider, NInput, NSpin, NStep, NSteps, useMessage } from 'naive-ui'
import QrcodeVue from 'qrcode.vue'
import type { TwoFAConfig } from '@/components/admin/model'
import { fetchDisableUser2FA, fetchGetUser2FA, fetchVerifyUser2FA } from '@/api'

const ms = useMessage()
const loading = ref(false)
const saving = ref(false)
const config = ref<TwoFAConfig>()

async function fetchConfig() {
  try {
    loading.value = true
    const { data } = await fetchGetUser2FA<TwoFAConfig>()
    config.value = data
  }
  finally {
    loading.value = false
  }
}

async function update2FAInfo() {
  saving.value = true
  try {
    if (!config.value)
      throw new Error('Invalid')
    const result = await fetchVerifyUser2FA(config.value.secretKey, config.value.testCode)
    await fetchConfig()
    ms.success(result.message as string)
  }
  catch (error: any) {
    ms.error(error.message)
  }
  saving.value = false
}

async function disable2FA() {
  saving.value = true
  try {
    if (!config.value)
      throw new Error('Invalid')
    const result = await fetchDisableUser2FA(config.value.testCode)
    await fetchConfig()
    ms.success(result.message as string)
  }
  catch (error: any) {
    ms.error(error.message)
  }
  saving.value = false
}

onMounted(() => {
  fetchConfig()
})
</script>

<template>
  <NSpin :show="loading">
    <div class="p-4 space-y-5 min-h-[200px]">
      <div class="space-y-6">
        <div class="flex items-center space-x-4">
          <div class="flex-1">
            Two-step verification is an additional security layer that enhances the security of your login experience. When two-step verification is enabled, you will be prompted to enter a dynamic verification code every time you want to log into your account.
            <br> Current Status:
            <span v-if="!config || !config.enabled" style="color: red;">Disabled</span>
            <span v-if="config && config.enabled" style="color: rgb(22, 183, 65);">Enabled</span>
          </div>
        </div>
        <div v-if="config && config.enabled" class="flex flex-col space-y-2">
          <div>
            <p class="text-xs text-black/60 dark:text-white/50 text-left">
              Enter the 6-digit dynamic verification code to disable the two-step verification.<br>
              Note: If you have lost your phone or cannot use the dynamic verification code, please contact at <a href="mailto:support@axiomaibd.com" class="text-[#f59e0b]">support@axiomaibd.com</a>
            </p>
          </div>
          <div class="w-[200px]">
            <NInput
              :value="config && config.testCode"
              placeholder="Enter 6-digit code"
              @input="(val) => { if (config) config.testCode = val }"
            />
          </div>
        </div>
        <div v-if="config && config.enabled" class="flex items-center space-x-4">
          <div class="flex flex-wrap items-center gap-4">
            <NButton
              :loading="saving" type="error" :disabled="!config || !config.testCode || config.testCode.length !== 6"
              @click="disable2FA()"
            >
              {{ $t('setting.disable2FA') }}
            </NButton>
          </div>
        </div>
        <NDivider v-if="!config || !config.enabled" />
        <div v-if="!config || !config.enabled" class="flex items-center space-x-4">
          <div class="flex-1">
            <NSteps vertical>
              <NStep
                title="Installation of the Authenticator App"
                description="Install an authenticator app: Google Authenticator, Microsoft Authenticator, Authy, etc."
              />
              <NStep
                title="Configure to generate verification code"
              >
                Open the Authenticator App and click "Scan QR Code" to scan the QR code.
                <br><br>
                <QrcodeVue :value="config?.otpauthUrl" :size="150" level="H" />
                <br>Note: Authenticator can't scan the verification code? Manually add the following account information:<br> Account: <a class="font-bold">{{ config?.userName }}</a><br> Key: <a class="font-bold">{{ config?.secretKey }}</a>
              </NStep>
              <NStep
                title="Verify and enable"
              >
                Please enter the 6-digit dynamic verification code generated by the Authenticator App to enable the two-step verification.
                <br>
                <div class="flex items-center space-x-4">
                  <div class="w-[200px]">
                    <NInput
                      :value="config && config.testCode"
                      placeholder="Enter 6-digit code"
                      @input="(val) => { if (config) config.testCode = val }"
                    /><br><br>
                    <NButton
                      :loading="saving" type="primary" :disabled="!config || !config.testCode || config.testCode.length !== 6"
                      @click="update2FAInfo()"
                    >
                      {{ $t('setting.enable2FA') }}
                    </NButton>
                  </div>
                </div>
                <br>FAQ: How do I turn off two-step verification?<br>1. After logging in, go to settings > 2FA and enter the 6-digit verification code.<br>2. Contact at <a href="mailto:support@axiomaibd.com" class="text-[#f59e0b]">support@axiomaibd.com</a> to reset your password to disable two-step verification.
              </NStep>
            </NSteps>
          </div>
        </div>
        <div v-if="!config || !config.enabled" class="flex items-center space-x-4">
          <div class="flex flex-wrap items-center gap-4" />
        </div>
      </div>
    </div>
  </NSpin>
</template>
