version: '3'

services:
  database:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: axiomdb

volumes:
  mongodb: {}
