version: '3'

services:
  app:
    image: deepspacelab.azurecr.io/axiomnode:latest
    container_name: AxiomNode
    restart: unless-stopped
    ports:
      - 10829:10829
    depends_on:
      - database
    environment:
      TZ: Asia/Dhaka

      # OpenAI API Base URL | Default: https://api.openai.com | Available: https://api.hypere.app
      OPENAI_API_BASE_URL: 

      # OpenAI API Key - https://platform.openai.com/overview | When using https://api.hypere.app get api key from https://discord.gg/ftSSNcPQgM
      OPENAI_API_KEY: 
      
      # ChatGPTAPI or ChatGPTUnofficialProxyAPI
      OPENAI_API_MODEL: 

      # OpenAI API Model - https://platform.openai.com/docs/models | Default: gpt-3.5-turbo
      OPENAI_CHAT_MODEL: 
      
      # Change this to an `accessToken` extracted from the ChatGPT site's `https://chat.openai.com/api/auth/session` response
      OPENAI_ACCESS_TOKEN: 

      # Reverse Proxy - Available when using accessToken | Default: https://ai.fakeopen.com/api/conversation
      API_REVERSE_PROXY: 

      # Timeout in milliseconds (optional). Which will also abort the underlying HTTP request Default: 100000
      TIMEOUT_MS: 

      # Rate Limit | Default: 0 (unlimited)
      MAX_REQUEST_PER_HOUR: 
      
      # Socks Proxy Host
      SOCKS_PROXY_HOST: 
      
      # Socks Proxy Port
      SOCKS_PROXY_PORT: 
      
      # Socks Proxy Username
      SOCKS_PROXY_USERNAME: 
      
      # Socks Proxy Password
      SOCKS_PROXY_PASSWORD: 
      
      # HTTPS PROXY
      HTTPS_PROXY: 

      # Debug Mode | set 'true' to disable debug mode
      DISABLE_DEBUG: 
      
      # MONGODB_URL=mongodb://username:password@hostname:port
      MONGODB_URL: 'mongodb://root:104382009@database:27017'

      # JWT secret key | Empty key will disable authentication system
      AUTH_SECRET_KEY: 

      # ----- Only valid after setting AUTH_SECRET_KEY begin ----
      # Allow anyone register
      REGISTER_ENABLED: false

      # The site domain for registration account verification. Don't use '/' at the end.
      SITE_DOMAIN: https://subdomain.domain.com

      # Allowed Email Providers, If it is empty, any mailbox is allowed
      # REGISTER_MAILS=@gmail.com,@icloud.com,@outlook.com
      REGISTER_MAILS: '@gmail.com,@icloud.com,@outlook.com'

      # Root user email
      ROOT_USER: 
      
      # Password salt
      PASSWORD_MD5_SALT: tastysalt
      
      # Mail Settings
      SMTP_HOST: smtp.mailgun.org
      SMTP_PORT: 465
      SMTP_TSL: true
      SMTP_USERNAME: 'SMTP_USERNAME'
      SMTP_PASSWORD: 'SMTP_PASSWORD'
    links:
      - database

  database:
    image: mongo
    container_name: AxiomDB
    restart: always
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 104382009
      MONGO_INITDB_DATABASE: axiomdb

volumes:
  mongodb: {}
