version: '3'

services:
  app:
    image: registry.octocarbon.codes/axiomnode:latest
    container_name: AxiomNode
    restart: unless-stopped
    ports:
      - 10829:10829
    depends_on:
      - database
    environment:
      TZ: Asia/Dhaka

      # Timeout in milliseconds (optional). Which will also abort the underlying HTTP request Default: 100000
      TIMEOUT_MS: 

      # Rate Limit | Default: 0 (unlimited)
      MAX_REQUEST_PER_HOUR: 
      
      # Socks Proxy Host
      SOCKS_PROXY_HOST: 
      
      # Socks Proxy Port
      SOCKS_PROXY_PORT: 
      
      # Socks Proxy Username
      SOCKS_PROXY_USERNAME: 
      
      # Socks Proxy Password
      SOCKS_PROXY_PASSWORD: 

      # Debug Mode | set 'true' to disable debug mode
      DISABLE_DEBUG: 
      
      # MONGODB_URL=mongodb://username:password@hostname:port
      MONGODB_URL: 'mongodb://root:104382009@database:27017'

      # JWT secret key | Empty key will disable authentication system
      AUTH_SECRET_KEY: 

      # ----- Only valid after setting AUTH_SECRET_KEY begin ----
      # Allow anyone to signup
      REGISTER_ENABLED: false

      # Enable signup application review
      REGISTER_REVIEW: false

      # The site domain for registration account verification. Don't use '/' at the end.
      SITE_DOMAIN: https://subdomain.domain.com

      # Allowed Email Providers, If it is empty, any mailbox is allowed
      # REGISTER_MAILS=@gmail.com,@icloud.com,@outlook.com
      REGISTER_MAILS: '@gmail.com,@icloud.com,@outlook.com'

      # Root user email
      ROOT_USER: 
      
      # Password salt
      PASSWORD_MD5_SALT: tastysalt
      
      # Mail Settings
      SMTP_HOST: smtp.mailgun.org
      SMTP_PORT: 465
      SMTP_TSL: true
      SMTP_USERNAME: 'SMTP_USERNAME'
      SMTP_PASSWORD: 'SMTP_PASSWORD'

      # Audit Settings
      # Whether to enable the review of sensitive words, because the response result is streaming, so there is no review for the time being | # https://ai.baidu.com/ai-doc/ANTIPORN/Vk3h6xaga
      AUDIT_ENABLED: false
      AUDIT_PROVIDER: baidu
      AUDIT_API_KEY: 
      AUDIT_API_SECRET: 
      AUDIT_TEXT_LABEL: 
    links:
      - database

  database:
    image: mongo
    container_name: AxiomDB
    restart: always
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 104382009
      MONGO_INITDB_DATABASE: axiomdb

volumes:
  mongodb: {}
