version: '3'

services:
  app:
    image: registry.octocarbon.codes/axiomnode:latest
    container_name: AxiomNode
    restart: unless-stopped
    ports:
      - 10829:10829
    depends_on:
      - database
    environment:
      TZ: Asia/Dhaka

      # Debug Mode | set 'true' to disable debug mode
      DISABLE_DEBUG:

      # Rate Limit | Default: 0 (unlimited)
      MAX_REQUEST_PER_HOUR:

      # Auth Rate Limit
      AUTH_MAX_REQUEST_PER_MINUTE:

      # MONGODB_URL=mongodb://username:password@hostname:port
      MONGODB_URL: 'mongodb://root:104382009@database:27017'

      # ----- Only valid after setting AUTH_SECRET_KEY begin ----
      # JWT secret key | Empty key will disable authentication system
      AUTH_SECRET_KEY:

      # Allow anyone to signup
      REGISTER_ENABLED: false

      # Enable signup application review
      REGISTER_REVIEW: false

      # Root user email
      ROOT_USER:

      # Password salt
      PASSWORD_MD5_SALT: tastysalt

    links:
      - database

  database:
    image: mongo
    container_name: AxiomDB
    restart: always
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 104382009
      MONGO_INITDB_DATABASE: axiomdb

volumes:
  mongodb: {}
