export enum authErrorType {
  ABNORMAL = 'SINGULARITY_SHUTDOWN',
  ABNORMAL2 = '503-ODD',
  NOTFOUND = 'GALACTIC_GHOST',
  PERMISSION = 'INTERSTELLAR_AUTHORIZATION_REQUIRED',
  UNVERIFIED = 'COSMIC_CLEARANCE_REQUIRED',
  USDV = 'USDV_CLEVER',
}

export enum authInfoType {
  AASV = 'AASV',
  PERMISSION = 'PERMISSION_APR',
  PERMISSION2 = 'PERMISSION_CLEVER',
  PRSC = 'PRSC',
  SRPM = 'SRPM',
  UNVERIFIED = 'UNVERIFIED',
  UNVERIFIED2 = 'UNVERIFIED_CHANNEL_SU',
  VERIFIED = 'VERIFIED',
}
